### ISSUE TITLE
We would need to be able both to do the backorder and/or get notified once the goods is in stock.

### ISSUE THREAD

**Issue by pavelsodomka** [oopo-io/odoo-apps#1]
Can this be done by the app ? Thanks a lot

Pavel Sodomka

**Comment by oopoio** [comment]
Yes, 

If you set as 'Sell regardless of inventory' and 'Always Show Notify Button' you can sell without inventory and also notify the customer.

![image](https://user-images.githubusercontent.com/63275648/78627629-98d7f880-7857-11ea-946c-74400f2e7bd0.png)
